# Matrix diagonalization
** Burton Rosenberg, May 2017**

A matrix is a linear map between vector spaces. To understand the transformation, we consider the matrix as an _endomorphism_, a map of the vector space back to itself, and look for invariant subspaces. An _invariant subspace_ is a linear subspace of the vector space that is mapped by the matrix back into itself. In particular, if the invariant supspace is one dimensional, that on that subspace the matrix acts as a pure scaling.

To find a one dimensional invariant subspace, we write down the property of a vector in such a subspace:
$$
     \lambda v = M v
$$
where $\lambda$ is a scalar and $M$ is the matrix. The vector $v$ and the scalar $\lambda$ are to be determined. The  $v$,  \lambda$ pair are called the _eigvenvector_ along with its associated _eigenvalue_, respectively.

### Examples:

Find three distinct eigenvalue-eigenvectors pairs of this matrix:

In [30]:
%pylab inline

import numpy as np

def isgood(m,evect,evalue):
    return np.array_equal(m.dot(evect), evalue*evect)

m1 = np.array([[1,0,0],[0,2,0],[0,0,3]])


Populating the interactive namespace from numpy and matplotlib


Make the tests true. BTW, eigenvectors must be non-zero, so the fact that the tests are passed by $v=0$ and $e=0$ does not count.


In [39]:
"""
Name me some eigenvalues
"""

v1 = np.ones(3) ; e1 = 0
v2 = np.ones(3) ; e2 = 0
v3 = np.ones(3) ; e3 = 0 

print isgood(m1,v1,e1)
print isgood(m1,v2,e2)
print isgood(m1,v2,e2)


False
False
False


### Uniqueness of eigenvectors

Congratulations on finding the eigenvectors and eigenvalues. 

Note that the eigenvalues are distinct. This means that the three eigenvectors you found are all the possible eigenvectors. Consider matrix M2.

Make the tests true.

In [83]:
"""
The challenge: 

Find the eigenspace of m2. Respond with v4, v5, e45 so that v4 and v5 
span the eigenspace, and e45 is the common eigenvalue of v4 and v5.
"""

m2 = np.array([[3,0,0],[0,3,0],[0,0,4]])

v4 = np.array([0,0,0],dtype="float")
v5 = np.array([0,0,0],dtype="float")
e45 = 0.0

def linear_mix(a,v,b,w):
    """
    Given floats a and b, and vectors v and w, return a*v+b*2
    (you have to write this)
    """
    return np.ones(len(v))

## the tests

import random

def test_linear_mix():
    tvs = np.array([random.randint(0,100) for i in range(9)]).reshape(3,3)
    tal = 0.25
    tlin = linear_mix(tal,tvs[0],1.0-tal,tvs[1])
    return tlin.dot(tvs[2]) == (tal*tvs[2].dot(tvs[0])+(1.0-tal)*tvs[2].dot(tvs[1]))

def test_eigenspace(v4,v5,e45):
    if np.array_equal(v4,v5):
        print "ErrorL vectors are not distinct"
        return False
    for alpha in np.linspace(0,1,5,dtype=float):
        v = linear_mix(alpha,v4,1.0-alpha,v5)
        if not isgood(m2,v,e45):
            print "Error: vector is not in an invariant subspace"
            return False
    return True

print "Dot product test:", test_linear_mix()
result=test_eigenspace(v4,v5,e45)
print "Eigenspace test:", result

 

Dot product test: False
Vectors are not distinct
Eigenspace test: False


### Solving for eigenvectors

The equation defining eigenvectors can be rearranged:
$$
(\lambda\, I - M) \cdot v = 0
$$
For a non-zero $v$ to solve this equation the matrix must be singular, and the vector in the left null space. With $\lambda$ considered an unknown, that leds to solving the equation,
$$
det(\lambda\,I-M) = 0
$$
This is called the _characteristic equation_.
While it is tedious to write out the equation for the determinate in the unknown $\lambda$, we do know that it is a cubic in $\lambda$, and therefore has three solutions over the complex numbers.

We also know that the complex solutions, if any, will come in conjugate pairs, and therefore at least on eigenvalue is real.

Write the code to verify you eigenvalues given in the above challenge. See the [numpy reference for linalg.det](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.linalg.det.html)

In [85]:
def char_eqn(m,lmb):
    """
    Returns True if lmb is a root of the characteristic equation of matrix m.
    """
    return False

print char_eqn(m1,e1),char_eqn(m1,e2),char_eqn(m1,e3)

False False False


### Diagonalization part 1: eigenvalues

Find the eigenvalues of matrix m3. _Hint:_ you can always binary search for the zero. There is probably a numby call that calculates eigenvalues.

In [130]:
m3 = np.array([[ 3.6,0.6,-0.2],[0.6,3.6,-0.2],[-0.4,-0.4,4.8]])

e31 = 0.0
e32 = 0.0
e33 = 0.0

print char_eqn(m3,e1),char_eqn(m3,e2),char_eqn(m3,e3)

np.linalg.svd(m3)

False False False


(array([[ -3.15153646e-01,   6.32991453e-01,  -7.07106781e-01],
        [ -3.15153646e-01,   6.32991453e-01,   7.07106781e-01],
        [  8.95185098e-01,   4.45694560e-01,  -1.80411242e-16]]),
 array([ 5.02183692,  3.98260643,  3.        ]),
 array([[ -3.34881315e-01,  -3.34881315e-01,   8.80743441e-01],
        [  6.22779660e-01,   6.22779660e-01,   4.73593698e-01],
        [ -7.07106781e-01,   7.07106781e-01,  -5.55111512e-17]]))

### Diagonalization part 2: eigenvectors

The eigenvectors are the three vectors that solve the equation $(\lambda\,I-M)\cdot v_i=0$.

This can be done by backsolving, or using a numby call to solving a matrix equation. In this case, this should be the vector in the one-dimensional null space of the matrix resulting from evaluating the characteristic equation at the eigenvalue. When "shifted" away from singularity, it becomes the invariant space.

Find these three vectors for m3.

In [ ]:
v31 = np.array([0,0,0])
v32 = np.array([0,0,0])
v33 = np.array([0,0,0])

def eval_ce(lm,m,v):
    return (lm*np.eye(3)-m).cdot(v)

print eval_ce(m3,e31,c31).array_equal(np.zeros(3)),
    eval_ce(m3,e32,c32).array_equal(np.zeros(3)),
    eval_ce(m3,e32,c32).array_equal(np.zeros(3))


### Diagonalization part 3: Singular Value Decomposition

Because the eigenvalues are distinct, the eigenvectors must be linearly independent (why?). That means they must span the three dimensional space, and can be used as an alternative coordiante system. That is, for a vector $v$, there is a unique triple $(x,y,z)$ such that
$$
v = x v_1 + y v_2 + z v_3
$$
So this triple is the coordinate of $v$ in the coordinate system with basis $(v_1,v_2,v_3)$.

So decomposed, the vector passes through the transformation with each coordinate scaled individualy by the eigenvalue associated with the eigenvector. The new coordiantes can then be reexpressed in the standard basis by applying the coordinate to the associated eigenvector then summing.

This can be carried out by hand, but it can also be found in the numby linear alegrebra package, under the name _singular value decomposition_. The SVD is the basis for many other statistical tests, and alternative decompositions differ in numerical stability, but not in the conceptual framework.

Write the SVD decomposition of m3. Note that the diagonal matrix is the diagonal of eigenvalues. 