## Python for REU 2019

_Burt Rosenberg, 12 May 2019_


### The Numpy Library

_Originally the notebook "The Numpy Library" dated May 2017_

Python is being used increasingly as a language for scientific computing because of its qualities as a programing language and because of community developed libraries extending the langauges abilities. One concern with using a powerful language like Python is that it loses the efficiency of languages which run "closer to the metal", although the analogy should be "closer to the silicon". For instance, programs written in C can be very efficient to run but they are not efficient to code. C codes slowly and requires extreme attention to detail.

The SciPy initiative attempts to solve this efficiency gap, and present powerful, efficient libraries of Python code for scientific programing. Some of these libraries are written in C to truely extend the way the language represents and manipulates data. These abilities are brought into your programs using an _import_ statement, naming a package or module that contains definitions. These then become avaiable for use in your program.

SciPy includes NumPy for numeric arrays, MatPlotLib for making graphs, and Pandas for tabularizing and cleaning data. In this page we talk about NumPy. The entire scipy library is described at [scipy.org](https://www.scipy.org/docs.html). One might also look at the [scipy-lectures](http://www.scipy-lectures.org/index.html) tutoral.

__Python Libraries__

Libraries in Python include packages and modules. Modules are files containing Python code that is made available for use with the _import statement_. Packages are collections of modules, represented as entire directory trees of modules. An import statement is of the form  import-as or from-import-as.

Import statements must first find the module in the system enviornment, then make the contents available by populating the local namespace. A simple _import module_ command finds a file with the same name as the module name and populates a local namespace of the same name as the module name. If one wishes the local namespace name to be different, use _import module as name-. 

The from form of the import statement, _from module import name as name_, operates by first looking up the module, then introducing namespaces one by one, according to the trailing name-as clauses.

Names are found by searching the system path. This path can be accessed using the path list of strings in the sys module.

In the following we import the (not scipy) sys library. More libraries can be found at https://docs.python.org/3/library/index.html. 



In [87]:
# find the sys module and make it available with namespace "sys"
import sys

print("\nthe Python version is -\n\t", sys.version)
print("\nthe search path for modules is -\n\t", sys.path)
print("\nthe platform is -\n\t",sys.platform)


the Python version is -
	 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

the search path for modules is -
	 ['', '/Users/ojo/anaconda3/lib/python36.zip', '/Users/ojo/anaconda3/lib/python3.6', '/Users/ojo/anaconda3/lib/python3.6/lib-dynload', '/Users/ojo/anaconda3/lib/python3.6/site-packages', '/Users/ojo/anaconda3/lib/python3.6/site-packages/aeosa', '/Users/ojo/anaconda3/lib/python3.6/site-packages/IPython/extensions', '/Users/ojo/.ipython']

the platform is -
	 darwin



## Numpy arrays



NumPy introduces the datatype _ndarray_, a multi-dimensional array of numbers. The ndarray improves on the list for efficiency and the collection methods it supports. That includes the notion of _universal functions_ and _broadcasting_. These concepts and methods make it very intuitive to us arrays for scientific computation. 
 
 


__Numpy features__

Numpy arrays support:

* Element-wise operations; 
* Indexing operations based on strides
* No-copy views when reshaping, when possible.
* Broadcasting;
* Ufuncts for arithmetic, logical, and common functions;
* Masking and fancy indexing

See the scipy.org numpy-1.12.0 [reference](https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.html)



In [88]:
# find the numpy module, and bring it is as namespace "np"
import numpy as np

# a ndarray can be created from a list
a_nd = np.array([i for i in range(11)],dtype=float)
print("\nthe class of a_nd is", a_nd.__class__.__name__)

print("a_nd = ", a_nd)
ones_nd = np.ones(len(a_nd))
print("ones_nd = ", ones_nd)

# numpy supports element-wise addition
print("a_nd+ones_nd=", a_nd + ones_nd)

# but also supports this sort of natural syntax for vectors
# (this is an example of broadcasting)
print("3*a_nd + 7 =", 3*a_nd+7)

# numpy supports ufuncs, which are functions applied to all individual elements
# in the ndarray by applying it to the ndarray.
print("log of each element in (a_nd+1) = \n\t", np.log(ones_nd+a_nd))


the class of a_nd is ndarray
a_nd =  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
ones_nd =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
a_nd+ones_nd= [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
3*a_nd + 7 = [ 7. 10. 13. 16. 19. 22. 25. 28. 31. 34. 37.]
log of each element in (a_nd+1) = 
	 [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527]


#### Arrays in C

The technology behind the ndarray is to wrap native arrays, as represented in C language, inside a Python object. To better understand ndarrays, we discuss how C handles arrays.

C language adopts a model of memory as a sequence of bytes. Each byte has an address, and given an address A, the following bytes in memory are at addresses A+1, A+2, etc. It is efficient from an address A and an index i, to store and fetch memory location A+i.

Other C data types are either primitive to the language, or user defined, and each requires one or multiple bytes in consecutive locations in memory for the storage of values of the type. The C keyword *sizeof* returns the number of bytes required for the type. C mandates a general scale of primitive types and that the type *char* occupies one byte, 
<pre>
1 == sizeof(char) &lt;= sizeof(short) &lt;= sizeof(long) &lt;= etc
</pre>
Except for char, the exact number of bytes for other types is not mandate, however, a common situation is short is 2 bytes, int is 4 bytes, long is 8 bytes, float is 8 bytes and and double is 16 bytes.
<p>
In C, and array of type T is a sequence of elements of type T arranged sequentially in memory. This allows that that i-th element of the sequece be located in memory according the the formula,
<pre>
a[i] = a + i * sizeof(type-of a).   
</pre>
For instance, if a[] is an array of int, and each int is 4 bytes, i.e. sizeof(int)==4, then the i-th element in the array is found at 4 * i bytes from the beginning of the array.

Multidimensional arrays, such as int [2][3] are understood as a sequence of arrays. The array of type int[2][3] is a sequence of 2 sequences, each of which is a sequence of 3 integers. Here is a picture

<pre>
 int int int.  int int int
+---+---+---+ +---+---+---+   sequences of three int's, each one after the other in memory
+-----------+ +-----------+   the array is two such sequences, one after the other in memory,
</pre>

As a further example, _int a[2][3][3]_ would be a sequence of 2 sequences of 3 sequences of 3 int's. Here is a picture:
<pre>
 +--+--+--+ +-+--+--+ +--+--+--+ +--+--+--+ +--+--+--+ +--+--+--+ seq of 3 int's
 +--------+ +-------+ +--------+ +--------+ +--------+ +--------+ seq of 3 int[3]'s
 +-----------------------------+ +------------------------------+ seq of 2 int[3][3]'s.
</pre>
<p>
Note then that in order of memory position, the rightmost index moves fastest in this C layout. That is, the elements occur from lowest address to highest as 
<pre>
a[0][0][0], a[0][0][1], a[0][0][2], a[0][1][0], a[0][1][1], ..., a[0][2][2], a[1][0][0], ... , a[1][2][2].
</pre>

#### Numpy stride and views


The ndarray type provided by the numby library is an efficient and flexible array for scientific computing. It contains only numbers or other arrays in a rectangular fashion. An ndarray is represented in memory as a block of memory, an indexing function (the array's shape) and an base type (some sort of number). The indexing function gives the number of dimensions, the size along each dimension, and a _stride_ indicating offsets between successive elements in a dimension. 


The ndarray is an object that contains a C-like array in a contiguous block of memory as well as the collection of indexing function that maps indices into the memory. This is captured in the _stride_ of each index, the 
number of bytes between consecutive elements in an array. C fixes the stride at compile time, and no introspective access to that stride, or way to change it. Python can introspect and reassign the stride when creating alternative _views_ of the same ndarray.

The strides for an ndarray can be retrived as the strides property of the ndarray object, and is a k-tuple of integers for a k-dimensional ndarray. The shape of an ndarray is in effect the collection of strides. A simple exercise is to call reshape(-1), which will flatten the ndarray shape into a one dimensional sequence of values.

<p>
A _view_ is an alternative indexing into an array. It might or might no be a copy, depending on whether the view is possible by manipulating strides alone, or applying transpose maps to the indices. For instance, the view generated by taking every other element in the array, given by the slice notation [::2], does not require a copy of the array, but simply doubles the stride in the particular dimension. The transpose operator exchanges the stride and shape values, creating a new view of the array without rewriting memory.


In [89]:
import numpy as np

a = np.arange(12)
b = a[::2].view()
print ("a.strides= {}, a.shape= {}\na= {}\nb.strides= {}, b.shape= {}\nb= {}\n".format(a.strides, 
    a.shape, a, b.strides, b.shape, b))
a.shape = (4,3)
b = a[::-2,::2].view()
print ("a.strides= {}, a.shape= {}\na= {}\nb.strides= {}, b.shape= {}\nb= {}\n".format(a.strides, 
    a.shape, a, b.strides, b.shape, b))
b = a.T.view()
a[0][0]=-1 # change an element in array a, and in array b as well, as it is a no-copy view of a.
print ("a.strides= {}, a.shape= {}\na= {}\nb.strides= {}, b.shape= {}\nb= {}\n".format(a.strides, 
    a.shape, a, b.strides, b.shape, b))

a.strides= (8,), a.shape= (12,)
a= [ 0  1  2  3  4  5  6  7  8  9 10 11]
b.strides= (16,), b.shape= (6,)
b= [ 0  2  4  6  8 10]

a.strides= (24, 8), a.shape= (4, 3)
a= [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b.strides= (-48, 16), b.shape= (2, 2)
b= [[ 9 11]
 [ 3  5]]

a.strides= (24, 8), a.shape= (4, 3)
a= [[-1  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b.strides= (8, 24), b.shape= (3, 4)
b= [[-1  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]



In [98]:
import numpy as np

# no copy views. a bit different than Python slices

a = np.arange(13)
# in Python this would be a shallow copy
# in numpy it is a non-copy view
b = a[:]
b[0] = 37.5
print(a)

[37  1  2  3  4  5  6  7  8  9 10 11 12]


#### Reshaping arrays and C vs. Fortran memory

__N.B. _this is advanced material and probably not of value to you immediately. you can skip to the next section_.__

Generally reshaping an array returns a view. The reshaping is done by manipulating the index function, leaving the data values in memory alone. However, it might require a copy, and if so, the reshape method will make a copy, but assigning directly to the reshape property will give a ValueError.

Note the difference between how slices affect Python lists and ndarrays. Where as slices of a python list copy the list, the slice notation applied to an ndarray is a _no copy view_ of the ndarray. A mapping from the slice indexes directly into the original ndarray, and changes to the slice change the original array.

By default, numpy uses a stride of _row major order_, where the rightmost index has stride 1. This is the same order as C; however Fortran uses _column major order_, where the leftmost index has stride 1.  

The shape is a tuple, and note that a singleton tuple is denoted (a,), with the comma. Else this is an integer, which will be converted in the obvious way into a tuple when in the context of a tuple.

In [90]:
# example of reshaping with and without copying

a = 1 + np.arange(6).reshape([2,3])
b = a.reshape(-1)
c = a.reshape(-1,order='F')

# because we wish to read out the elements in fortran order when inserting them sequentially in c, 
# it is not possible that c is a view of a. however, b can be. we prove this:

print("a =\n{}\nb= {}, c= {}".format(a,b,c))
a[0,0]=-1
print("a =\n{}\nb= {}, c= {}".format(a,b,c))
print("\nWe hold these truths to be self-evident: {} {}\n".format(
    b[0]==a[(0,0)], c[0]==-a[(0,0)])  # note, the true index of an array is a tuple, but syntatic sugar is available
)

a =
[[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6], c= [1 4 2 5 3 6]
a =
[[-1  2  3]
 [ 4  5  6]]
b= [-1  2  3  4  5  6], c= [1 4 2 5 3 6]

We hold these truths to be self-evident: True True



The shape property is settable, and this leads to some simplification of the API:

In [91]:
import numpy as np ;

m = np.array([1,2,3])
print ("shape of m = ", m.shape)
print ("m=", m)
m.shape = (3,1)
print ("shape of m = ", m.shape)
print ("m=", m)


shape of m =  (3,)
m= [1 2 3]
shape of m =  (3, 1)
m= [[1]
 [2]
 [3]]



### Broadcasting

Broadcasting allows for intuitive behavoir such as the multiplication of a scalar times a vector. In mathematics, the operation scales the vector, equivalently, it mutliplies each entry of the vector by the scalar,
<pre>
 &lambda; (x,y,z) = (&lambda; x, &lambda; y, &lambda; z )
</pre>
However, the Numpy package explains this behavoir as an example of _broadcasting_. Because the shape of the scalar is (1,), and the shape of the vector is (3,), and operations are done element-wise, the (1,) is promoted to a (3,) by broadcasing the singel value into all three places when extending.
<p>
The general process is to see whether two ndarrays are _broadcast compatible_, and if they are, they are brougth to a common shape by repeating copies of full subelements of the ndarray to achieve equal shapes.
<p>
Broadcast-compatible arrays are those whose shapes either agree on any dimension, or one dimension is 1, or they differ in dimensions, in which case the missing dimensions are considers 1's.
<p>
_Example:_ A scalar, (1,) against a vector (d,), d>0, is broadcast compatible, and the scalar is extended to (d,).
<p>
A vector, (d,) against a matrix (r,c), is broadcast compatible if either d=1, or d=c. The vector is first given equal dimensions but writing it as (1,d), If d=1 first the single colum of (1,1) is broadcast c times to give the shape (1,c), then (or if d=c to being with), the single row of (1,c) is repeated r times to give the shape (r,c). 

In [92]:
vec = np.ones((4,))
scalar = np.array([1])
print("scalar: shape=",scalar.shape, "\nvalue=\n", scalar, "\n")
bc = scalar + np.zeros(vec.shape,dtype=int)
print("scalar broadcasted to shape=",bc.shape, "\nvalue=\n", bc, "\n")
print ("We hold these truths to be self-evident:", np.array_equal(vec,bc),"\n")

mat = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
vec = np.array([1,2,3,4])
print("vec: shape=",vec.shape, "\nvalue=\n", vec, "\n")
bc = vec + np.zeros(mat.shape,dtype=int)
print("vec broadcasted to shape=",bc.shape, "\nvalue=\n", bc, "\n")
print ("We hold these truths to be self-evident:", np.array_equal(mat,bc),"\n")

col_vec = np.array([[1],[2]])
print("col vec: shape=",col_vec.shape, "\nvalue=\n", col_vec, "\n")
m = np.zeros((3,2,4),dtype=int)
bc = col_vec + m
print("col vec broacasted to shape ",m.shape, "\nvalue=\n", bc, "\n")

mat = np.zeros((4,3),dtype=int)
vec = np.array([1,2,3])
vec_t = np.array([[1],[2],[3],[4]])
print("vec: shape=",vec.shape, "\nvalue=\n", vec, "\n")
print("col vec: shape=",vec_t.shape, "\nvalue=\n", vec_t, "\n")
vec = vec + mat
vec_t = vec_t + mat
print("broadcasting vec to shape",vec.shape, "gives:\n", vec, "\n")
print("broadcasting col vec to shape",vec_t.shape, "gives:\n", vec_t, "\n")
print("example where both operands submit to broadcasting:\nvec * col_vec =\n",vec*vec_t)



# a 3x3x3 cube, where the vertices are assigned 3, the edges 2, the interior face 1, and the body interior 0
a = np.array([1,0,1])
print("\n\nsumming a [1,0,1] row vector, a [1,0,1] column vector and a [1,0,1] depth vector",
      "\nwith broadcasting gives a 3 x 3 x 3 cube where vertices score 3, edges score 2, ",
      "\nfaces score 1, and the volume scores 0:\n\n{}".format(
    a + a.reshape((3,1))+a.reshape((3,1,1))))



scalar: shape= (1,) 
value=
 [1] 

scalar broadcasted to shape= (4,) 
value=
 [1 1 1 1] 

We hold these truths to be self-evident: True 

vec: shape= (4,) 
value=
 [1 2 3 4] 

vec broadcasted to shape= (3, 4) 
value=
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]] 

We hold these truths to be self-evident: True 

col vec: shape= (2, 1) 
value=
 [[1]
 [2]] 

col vec broacasted to shape  (3, 2, 4) 
value=
 [[[1 1 1 1]
  [2 2 2 2]]

 [[1 1 1 1]
  [2 2 2 2]]

 [[1 1 1 1]
  [2 2 2 2]]] 

vec: shape= (3,) 
value=
 [1 2 3] 

col vec: shape= (4, 1) 
value=
 [[1]
 [2]
 [3]
 [4]] 

broadcasting vec to shape (4, 3) gives:
 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]] 

broadcasting col vec to shape (4, 3) gives:
 [[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]] 

example where both operands submit to broadcasting:
vec * col_vec =
 [[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]


summing a [1,0,1] row vector, a [1,0,1] column vector and a [1,0,1] depth vector 
with broadcasting gives a 3 x 3 x 3 cube where vertices score 3, edg

#### Ufuncs

Universal functions are distributed elementwise over each element in an array. This includes some operators, and other standard functions that have been elevated to become ufuncs.

In [93]:
import numpy as np
import math


def logical_looping(a,b):
        t = True
        for i in range(len(a)):
                t = t and (a[i]>b[i])
        return t
    
def logical_ufunc(a,b):
    return np.all(a>b)


def arithmetic_looping(a,b):
        for i in range(len(a)):
                a[i] + b[i]
        return a
    
def arithmetic_ufunc(a,b):
    return a+b

def applysin_looping(s):
    for f in s:
        math.sin(f)

def applysin_ufunc(s):
    np.sin(s)  # note it is not math.sin, but np.sin

a = np.ones(1000000)
b = np.zeros(1000000)

a_list = [0.0 for i in range(1000000)]
b_list = [ 1.0 for i in range(1000000)]


print("\nlogical using looping over ndarray")
%time logical_looping(a,b)
print("\nlogical using ufunc")
%time logical_ufunc(a,b)

print("\narithmetic using looping over a list")
%time arithmetic_looping(a_list,b_list)
print("\narithmetic using looping over ndarray")
%time arithmetic_looping(a,b)
print("\narithmetic using ufunc")
%time arithmetic_ufunc(a,b)

mu, sigma = 0, 0.1
s = np.random.normal(mu, sigma, 1000000)

print("\nmath.sin and looping over ndarray")
%time applysin_looping(s)
print("\nnp.sin and ufunc's")
%time applysin_ufunc(s)




logical using looping over ndarray
CPU times: user 234 ms, sys: 26.9 ms, total: 261 ms
Wall time: 261 ms

logical using ufunc
CPU times: user 1.82 ms, sys: 885 µs, total: 2.7 ms
Wall time: 1.43 ms

arithmetic using looping over a list
CPU times: user 82.8 ms, sys: 11.7 ms, total: 94.5 ms
Wall time: 90.6 ms

arithmetic using looping over ndarray
CPU times: user 247 ms, sys: 10.7 ms, total: 257 ms
Wall time: 272 ms

arithmetic using ufunc
CPU times: user 3.22 ms, sys: 3.35 ms, total: 6.56 ms
Wall time: 5.67 ms

math.sin and looping over ndarray
CPU times: user 134 ms, sys: 2.36 ms, total: 136 ms
Wall time: 142 ms

np.sin and ufunc's
CPU times: user 6.36 ms, sys: 830 µs, total: 7.19 ms
Wall time: 6.17 ms


#### Masking and fancy indexing


In [105]:
import numpy as np

print("*** Masking examples ***")
a = np.array([7*i%13 for i in range(13)])
print(a)
b = a[a<4]
print(b)
c = np.arange(len(a))
print(c)
print(c[a%2==0])

print("*** Fancy Indexing")

print(a[[11,1,5]])
print(c[[11,1,5]])


*** Masking examples ***
[ 0  7  1  8  2  9  3 10  4 11  5 12  6]
[0 1 2 3]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  3  4  7  8 11 12]
*** Fancy Indexing
[12  7  9]
[11  1  5]


# C Language Arrays

Numpy wraps C language arrays in a Python framework. Here we look at raw C, and give examples has C handles arrays natively.






### C review

As numpy is a "cut-through" to C code and stuctures, so that Python may benefit from C's strengths and efficiency, we will pause to consider the row major ordering of C arrays.

A one dimensional array of C type X, be it int, long, float, double, or any other types, is an indexed sequence of elements, each of the same byte width. An array of 32 bit int's will consist of 4 times as many bytes as elements, and as access proceeds from the i-th to the i-th plus one element, the memory access is advanced by 4 bytes.

A two dimensional array is a sequence of one dimensional arrays. The byte width of each element as accessed by successive indices in the first (leftmost) index is the entire size of the one dimensional array describd the by the second (rightmost) index and the data width of the base type. An array described as _int a[4][3]_ is a sequence of 4 3-vectors of 32 bit integers, so that the byte distance betweeen _a[2][0]_ and _a[3][0]_ is 12 bytes. 

For a generic index of _a[i][j]_, the byte stride for the i-index is 12 and the byte stride for the j-index is 4. Above when I spoke of stride 1, for simplicity that was a stride defined by a unit of bytes needed for the base type. In that definition, i strides by 3 and i stides by 1.

It can be observed that accessig a large array along stride 1 is faster than accessing the array any other stride. The memory caching techniques employed by CPU's fetch memory contents from main memory in large buckets called _cache lines_. A single memory fetch cycle might bring into fast L3 cache several elements of the array that are close in stride. If accessing an array along stride, multiple elements share the cost of a complete memory fetch. Otherwise a complete memory fetch is required for each array element accessed.





In [95]:

#include<stdio.h>
#include<stdlib.h>
#include<assert.h>

/*
 * example of multidimensional arrays
 * author: bjr
 * created: 26 sep 2017
 * last update: 
 *
 */

/*
	This program demonstrates the typing syntax for C 
	multidimensional arrays. 

	The example is: a[i][j][k] == *(k+*(j+*(k+a)))

	in this case, a is of type [][j][k] of X, where X is 
	some base type. each *(a+k) is a [][k] of X, and each
	*(*(a+k)+j) is a [] of X. 

	Finally *(*(*(a+k)+j)+i) is of type X, as is a[i][j][k].

	The typing is strong, as sizeof(*a) and sizeof(**a), will
	show. The entire number of bytes of the subsection of 
	array in the remaining dimensions are counted. And "pointer
	subtraction" will properly account for how many objects
	occur between the two pointers, not how many raw bytes.

*/

int main(int argc, char * argv[]) {

	int a[4] ;
	int i, j, k ;

	   char * acp0, * acp1 ;
		acp0 = (char *) a ;
		acp1 = (char *) (a+1) ;
	
		assert( 1==((a+1)-a)) ;
		printf( "%d: the above assert will be good\n", __LINE__) ;

		assert( sizeof(int) == (acp1-acp0)) ;
		printf( "%d: the above assert will be good\n", __LINE__) ;

		// the notation a[i] is equivalent to *(a+i)

		a[3] = 47 ;
		assert( *(a+3) == 47 ) ;
		printf( "%d: the above assert will be good\n", __LINE__) ;
		*(a+3) = 74 ;
		assert( a[3] == 74 ) ;
		printf( "%d: the above assert will be good\n", __LINE__) ;

   /*******************************/

		int m[3][2] ;

		for (i=0;i<6;i++) 
			*((*m)+i) = i ; // m is a **int, a sequence of a sequence of ints, so *m is a sequence of ints.
			// therefore, (*m)+i will be interpreted as the location of i-th integer in a sequence, with base 
			// a m. the final star *((*m)+i) reduces the type from sequene of int to int.

		for (i=0;i<3;i++)
			for (j=0;j<2;j++) printf("%d ", m[i][j]) ;
		printf("\n") ;

		int (*n)[2] ; // n is a sequence of 2 vectors of ints.
		n = m ; 

		printf("sizeof m=%lu, sizeof m[0]=%lu, sizeof m[0][0]=%lu\n", 
		sizeof(m), sizeof(m[0]), sizeof(m[0][0])) ;
		
		for (i=0;i<3;i++)
			for (j=0;j<2;j++) printf("%d ", n[i][j]) ;
		printf("\n") ;

   /*******************************/

		int r[2][3][5] ;
		printf( "sizeof(r)=%lu, sizeof(r[0])=%lu, sizeof(r[0][0])=%lu,"
			" sizeof(r[0][0][0])=%lu\n", 
		sizeof(r), sizeof(r[0]), sizeof(r[0][0]), sizeof(r[0][0][0])) ;

		// *r reduces type as does r[0], and **r as does r[0][0] 
		assert( sizeof(r[0]) == sizeof(*r) && sizeof(r[0][0]) == sizeof (**r)) ;
		printf( "%d: the above assert will be good\n", __LINE__) ;
		assert( sizeof(r[10][20][30]) == sizeof(***r)) ;
		printf( "%d: the above assert will be good\n", __LINE__) ;

	for (i=0; i< 2*3*5; i++) {
		(**r)[i] = i ;
	}

	for (i=0;i<sizeof(r)/sizeof(*r);i++)
		for(j=0;j<sizeof(*r)/sizeof(**r);j++) 
			for (k=0;k<sizeof(**r)/sizeof(***r);k++)  {
				printf("r[%d][%d][%d]=%d\n", i,j,k, r[i][j][k]) ;
				assert(r[i][j][k]==*(k+*(j+*(i+r)))) ;
			}

	return 0 ;
}

/* RUN:
    
>>$ make
cc     matrices.c   -o matrices
./matrices
43: the above assert will be good
46: the above assert will be good
52: the above assert will be good
55: the above assert will be good
0 1 2 3 4 5 
sizeof m=24, sizeof m[0]=8, sizeof m[0][0]=4
0 1 2 3 4 5 
sizeof(r)=120, sizeof(r[0])=60, sizeof(r[0][0])=20, sizeof(r[0][0][0])=4
87: the above assert will be good
89: the above assert will be good
r[0][0][0]=0
r[0][0][1]=1
r[0][0][2]=2
r[0][0][3]=3
r[0][0][4]=4
r[0][1][0]=5
r[0][1][1]=6
r[0][1][2]=7
r[0][1][3]=8
r[0][1][4]=9
r[0][2][0]=10
r[0][2][1]=11
r[0][2][2]=12
r[0][2][3]=13
r[0][2][4]=14
r[1][0][0]=15
r[1][0][1]=16
r[1][0][2]=17
r[1][0][3]=18
r[1][0][4]=19
r[1][1][0]=20
r[1][1][1]=21
r[1][1][2]=22
r[1][1][3]=23
r[1][1][4]=24
r[1][2][0]=25
r[1][2][1]=26
r[1][2][2]=27
r[1][2][3]=28
r[1][2][4]=29
>>$ 

*/

IndentationError: unexpected indent (<ipython-input-95-14e54f37bf4e>, line 7)