## Python for REU 2019

_Burt Rosenberg, 12 May 2019_


### The Numpy Library

_Originally the notebook "The Numpy Library" dated May 2017_

Python is being used increasingly as a language for scientific computing because of its qualities as a programing language and because of community developed libraries extending the langauges abilities. One concern with using a powerful language like Python is that it loses the efficiency of languages which run "closer to the metal", although the analogy should be "closer to the silicon". For instance, programs written in C can be very efficient to run but they are not efficient to code. C codes slowly and requires extreme attention to detail.

The SciPy initiative attempts to solve this efficiency gap, and present powerful, efficient libraries of Python code for scientific programing. Some of these libraries are written in C to truely extend the way the language represents and manipulates data. These abilities are brought into your programs using an _import_ statement, naming a package or module that contains definitions. These then become avaiable for use in your program.

SciPy includes NumPy for numeric arrays, MatPlotLib for making graphs, and Pandas for tabularizing and cleaning data. In this page we talk about NumPy. The entire scipy library is described at [scipy.org](https://www.scipy.org/docs.html). One might also look at the [scipy-lectures](http://www.scipy-lectures.org/index.html) tutoral.

__Python Libraries__

Libraries in Python include packages and modules. Modules are files containing Python code that is made available for use with the _import statement_. Packages are collections of modules, represented as entire directory trees of modules. An import statement is of the form  import-as or from-import-as.

Import statements must first find the module in the system enviornment, then make the contents available by populating the local namespace. A simple _import module_ command finds a file with the same name as the module name and populates a local namespace of the same name as the module name. If one wishes the local namespace name to be different, use _import module as name-. 

The from form of the import statement, _from module import name as name_, operates by first looking up the module, then introducing namespaces one by one, according to the trailing name-as clauses.

Names are found by searching the system path. This path can be accessed using the path list of strings in the sys module.

In the following we import the (not scipy) sys library. More libraries can be found at https://docs.python.org/3/library/index.html. 



In [1]:
# find the sys module and make it available with namespace "sys"
import sys

print("\nthe Python version is -\n\t", sys.version)
print("\nthe search path for modules is -\n\t", sys.path)
print("\nthe platform is -\n\t",sys.platform)


the Python version is -
	 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

the search path for modules is -
	 ['', '/Users/ojo/anaconda3/lib/python36.zip', '/Users/ojo/anaconda3/lib/python3.6', '/Users/ojo/anaconda3/lib/python3.6/lib-dynload', '/Users/ojo/anaconda3/lib/python3.6/site-packages', '/Users/ojo/anaconda3/lib/python3.6/site-packages/aeosa', '/Users/ojo/anaconda3/lib/python3.6/site-packages/IPython/extensions', '/Users/ojo/.ipython']

the platform is -
	 darwin



## Numpy arrays

The high level of data abstration in Python exacts a price. Simple data items, such as integers or floating point numbers, are wrapped inside of objects that intervene between the programmer and the machine to allow a more conceptual use of the data object. Lists can sequence an arbitrary mixture of objects, so each element has to self-describe its type, and code must look up the proper handling of the data item on a per element basis.

At the other extreme, a language such as C is direct with its data types. An integer in memory is just enough information to shuttle it back and forth from the CPU to operate natively, 32 bit or 64 bit, on the integer. And arrays, rather than lists, need only a number of elements in their description, because it will be assumed that, at intervals of data type size, will lie in memory one floating point number after another, or one integer after another.

NumPy attempts to have the best of both worlds. NumPy objects, outwardly, will be Python objects, with all the convenience of highly conceptual data representation. Inside the object, however, the run-time cuts over to C data representation, and runs full throtle over a direct access to memory and data.

This presents restrictions. While a Python object tends to be polymorphous &mdash; support a range of types, even a heterogeneity of types, NumPy will give this up to optimize for the important cases of interest.



__Numpy features__


NumPy introduces the class _ndarray_, a multi-dimensional array of numbers. The ndarray improves on the list for efficiency and the collection methods it supports. That includes the notion of _universal functions_ and _broadcasting_. These concepts and methods make it very intuitive to us arrays for scientific computation. 
 
 
Numpy arrays support:

* Element-wise operations;
* Indexing operations based on strides;
* No-copy views when reshaping, when possible;
* Fast arrays based on a direct C-like representation;
* Broadcasting;
* Ufuncts for arithmetic, logical, and common functions;
* Masking and fancy indexing

See the scipy.org numpy-1.12.0 [reference](https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.html)



In [2]:
# find the numpy module, and bring it is as namespace "np"
import numpy as np

# a ndarray can be created from a list
a_nd = np.array([i for i in range(11)],dtype=float)
print("\nthe class of a_nd is", a_nd.__class__.__name__)

print("a_nd = ", a_nd)
ones_nd = np.ones(len(a_nd))
print("ones_nd = ", ones_nd)

# numpy supports element-wise addition
print("a_nd+ones_nd=", a_nd + ones_nd)

# but also supports this sort of natural syntax for vectors
# (this is an example of broadcasting)
print("3*a_nd + 7 =", 3*a_nd+7)

# numpy supports ufuncs, which are functions applied to all individual elements
# in the ndarray by applying it to the ndarray.
print("log of each element in (a_nd+1) = \n\t", np.log(ones_nd+a_nd))


the class of a_nd is ndarray
a_nd =  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
ones_nd =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
a_nd+ones_nd= [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
3*a_nd + 7 = [ 7. 10. 13. 16. 19. 22. 25. 28. 31. 34. 37.]
log of each element in (a_nd+1) = 
	 [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527]


__Timing__

The ndarray is supposed to be faster than Python, because it uses a more direct underlying array representation. These times give an indication to what measure this is true.

In [3]:
import numpy as np

# timings 


a_list = [1.0 for i in range(1000000)]
b_list = [ 2.0 for i in range(1000000)]
a_np = np.array(a_list)
b_np = np.array(b_list)

def list_add(a,b):
    c = [None]*len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

def numpy_add(a,b):
    c = a+b
    return c

def list_linear(a,m,b):
    c = [None]*len(a)
    for i in range(len(a)):
        c[i] = m * a[i] + b
    return c

def numpy_linear(a,m,b):
    c = m*a+b
    return c

%time list_add(a_list,b_list)
%time numpy_add(a_np,b_np)
%time list_linear(a_list,3.0,7.0)
%time numpy_linear(a_np,3.0,7.0)
a=1 # suppress output

CPU times: user 112 ms, sys: 18.9 ms, total: 131 ms
Wall time: 132 ms
CPU times: user 2.14 ms, sys: 1.33 ms, total: 3.47 ms
Wall time: 1.82 ms
CPU times: user 106 ms, sys: 9.87 ms, total: 116 ms
Wall time: 119 ms
CPU times: user 1.7 ms, sys: 533 µs, total: 2.24 ms
Wall time: 1.79 ms



### Broadcasting

Broadcasting allows for intuitive behavoir such as the multiplication of a scalar times a vector. In mathematics, the operation scales the vector, equivalently, it mutliplies each entry of the vector by the scalar,
<pre>
 &lambda; (x,y,z) = (&lambda; x, &lambda; y, &lambda; z )
</pre>
However, the Numpy package explains this behavoir as an example of _broadcasting_. Because the shape of the scalar is <code>(1,)</code>, and the shape of the vector is <code>(3,)</code>, and operations are done element-wise, the <code>(1,)</code> is promoted to a <code>(3,)</code> by broadcasing the single value into all three places when extending.
<p>
The general process is to see whether two ndarrays are _broadcast compatible_, and if they are, they are brougth to a common shape by repeating copies of full subelements of the ndarray to achieve equal shapes.
<p>
Broadcast-compatible arrays are those whose shapes either agree on any dimension, or one dimension is 1, or they differ in dimensions, in which case the missing dimensions are considers 1's.
<p>
_Example:_ A scalar, <code>(1,)</code> against a vector <code>(d,)</code>, d>0, is broadcast compatible, and the scalar is extended to <code>(d,)</code>.
<p>
A vector, <code>(d,)</code> against a matrix <code>(r,c)</code>, is broadcast compatible if either d=1, or d=c. The vector is first given equal dimensions but writing it as <code>(1,d)</code>, If d=1 first the single colum of <code>(1,1)</code> is broadcast c times to give the shape <code>(1,c)</code>, then (or if d=c to being with), the single row of <code>(1,c)</code> is repeated r times to give the shape <code>(r,c)</code>. 

In [4]:
vec = np.ones((4,))
scalar = np.array([1])
print("scalar: shape=",scalar.shape, "\nvalue=\n", scalar, "\n")
bc = scalar + np.zeros(vec.shape,dtype=int)
print("scalar broadcasted to shape=",bc.shape, "\nvalue=\n", bc, "\n")
print ("We hold these truths to be self-evident:", np.array_equal(vec,bc),"\n")

mat = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
vec = np.array([1,2,3,4])
print("vec: shape=",vec.shape, "\nvalue=\n", vec, "\n")
bc = vec + np.zeros(mat.shape,dtype=int)
print("vec broadcasted to shape=",bc.shape, "\nvalue=\n", bc, "\n")
print ("We hold these truths to be self-evident:", np.array_equal(mat,bc),"\n")

col_vec = np.array([[1],[2]])
print("col vec: shape=",col_vec.shape, "\nvalue=\n", col_vec, "\n")
m = np.zeros((3,2,4),dtype=int)
bc = col_vec + m
print("col vec broacasted to shape ",m.shape, "\nvalue=\n", bc, "\n")

mat = np.zeros((4,3),dtype=int)
vec = np.array([1,2,3])
vec_t = np.array([[1],[2],[3],[4]])
print("vec: shape=",vec.shape, "\nvalue=\n", vec, "\n")
print("col vec: shape=",vec_t.shape, "\nvalue=\n", vec_t, "\n")
vec = vec + mat
vec_t = vec_t + mat
print("broadcasting vec to shape",vec.shape, "gives:\n", vec, "\n")
print("broadcasting col vec to shape",vec_t.shape, "gives:\n", vec_t, "\n")
print("example where both operands submit to broadcasting:\nvec * col_vec =\n",vec*vec_t)



# a 3x3x3 cube, where the vertices are assigned 3, the edges 2, the interior face 1, and the body interior 0
a = np.array([1,0,1])
print("\n\nsumming a [1,0,1] row vector, a [1,0,1] column vector and a [1,0,1] depth vector",
      "\nwith broadcasting gives a 3 x 3 x 3 cube where vertices score 3, edges score 2, ",
      "\nfaces score 1, and the volume scores 0:\n\n{}".format(
    a + a.reshape((3,1))+a.reshape((3,1,1))))



scalar: shape= (1,) 
value=
 [1] 

scalar broadcasted to shape= (4,) 
value=
 [1 1 1 1] 

We hold these truths to be self-evident: True 

vec: shape= (4,) 
value=
 [1 2 3 4] 

vec broadcasted to shape= (3, 4) 
value=
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]] 

We hold these truths to be self-evident: True 

col vec: shape= (2, 1) 
value=
 [[1]
 [2]] 

col vec broacasted to shape  (3, 2, 4) 
value=
 [[[1 1 1 1]
  [2 2 2 2]]

 [[1 1 1 1]
  [2 2 2 2]]

 [[1 1 1 1]
  [2 2 2 2]]] 

vec: shape= (3,) 
value=
 [1 2 3] 

col vec: shape= (4, 1) 
value=
 [[1]
 [2]
 [3]
 [4]] 

broadcasting vec to shape (4, 3) gives:
 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]] 

broadcasting col vec to shape (4, 3) gives:
 [[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]] 

example where both operands submit to broadcasting:
vec * col_vec =
 [[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]


summing a [1,0,1] row vector, a [1,0,1] column vector and a [1,0,1] depth vector 
with broadcasting gives a 3 x 3 x 3 cube where vertices score 3, edg

#### Ufuncs

Universal functions are distributed elementwise over each element in an array. This includes some operators, and other standard functions that have been elevated to become ufuncs.

In [5]:
import numpy as np
import math


def logical_looping(a,b):
        t = True
        for i in range(len(a)):
                t = t and (a[i]>b[i])
        return t
    
def logical_ufunc(a,b):
    return np.all(a>b)


def arithmetic_looping(a,b):
        for i in range(len(a)):
                a[i] + b[i]
        return a
    
def arithmetic_ufunc(a,b):
    return a+b

def applysin_looping(s):
    for f in s:
        math.sin(f)

def applysin_ufunc(s):
    np.sin(s)  # note it is not math.sin, but np.sin

a = np.ones(1000000)
b = np.zeros(1000000)

a_list = [0.0 for i in range(1000000)]
b_list = [ 1.0 for i in range(1000000)]


print("\nlogical using looping over ndarray")
%time logical_looping(a,b)
print("\nlogical using ufunc")
%time logical_ufunc(a,b)

print("\narithmetic using looping over a list")
%time arithmetic_looping(a_list,b_list)
print("\narithmetic using looping over ndarray")
%time arithmetic_looping(a,b)
print("\narithmetic using ufunc")
%time arithmetic_ufunc(a,b)

mu, sigma = 0, 0.1
s = np.random.normal(mu, sigma, 1000000)

print("\nmath.sin and looping over ndarray")
%time applysin_looping(s)
print("\nnp.sin and ufunc's")
%time applysin_ufunc(s)




logical using looping over ndarray
CPU times: user 217 ms, sys: 28.6 ms, total: 246 ms
Wall time: 240 ms

logical using ufunc
CPU times: user 1.59 ms, sys: 1.23 ms, total: 2.83 ms
Wall time: 1.44 ms

arithmetic using looping over a list
CPU times: user 76.4 ms, sys: 6.37 ms, total: 82.7 ms
Wall time: 79.7 ms

arithmetic using looping over ndarray
CPU times: user 226 ms, sys: 11.3 ms, total: 237 ms
Wall time: 236 ms

arithmetic using ufunc
CPU times: user 2.73 ms, sys: 2.51 ms, total: 5.24 ms
Wall time: 4.37 ms

math.sin and looping over ndarray
CPU times: user 122 ms, sys: 2.2 ms, total: 124 ms
Wall time: 126 ms

np.sin and ufunc's
CPU times: user 8.44 ms, sys: 4.95 ms, total: 13.4 ms
Wall time: 11.2 ms


#### Masking and fancy indexing


In [6]:
import numpy as np

print("*** Masking examples ***")
a = np.array([7*i%13 for i in range(13)])
print(a)
b = a[a<4]
print(b)
c = np.arange(len(a))
print(c)
print(c[a%2==0])

print("*** Fancy Indexing")

print(a[[11,1,5]])
print(c[[11,1,5]])


*** Masking examples ***
[ 0  7  1  8  2  9  3 10  4 11  5 12  6]
[0 1 2 3]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  3  4  7  8 11 12]
*** Fancy Indexing
[12  7  9]
[11  1  5]


### Exercises

The following exercises ask that you implement as lists and as ndarrays various linear algebration operations.

In [7]:
import numpy as np


# fix my broken code!

# exercise in inner produces

# HINTS:
# if a is an nd-array, a.sum() is the sum of the elements of a

def inner_product_list(v,w):
    """
    v, w, lists of numbers
    """
    return 0.0

def inner_product(v,w):
    """
    v,w, ndarrays
    """
    return 0.0

def test_inner_product(n,epsilon):
    v = np.random.random(n)
    w = np.random.random(n)
    vl = v.tolist()
    wl = w.tolist()
    ans = np.inner(v,w)
    
    if math.isclose(inner_product_list(vl,wl),ans,abs_tol=epsilon):
        print("correct!")
    else:
        print("broken!")
    if math.isclose(inner_product(v,w),ans,abs_tol=epsilon):
        print("correct!")
    else:
        print("broken!")

def time_inner_product(n):
    v = np.random.random(n)
    w = np.random.random(n)
    vl = v.tolist()
    wl = w.tolist()

    print("")
    print("list version:")
    %time inner_product_list(vl,wl)
    print("ndarray version")
    %time inner_product(v,w)   
    

test_inner_product(100,0.001)
time_inner_product(10)
time_inner_product(10000)
#time_inner_product(10000000)


broken!
broken!

list version:
CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 10 µs
ndarray version
CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 8.82 µs

list version:
CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 7.87 µs
ndarray version
CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.15 µs


In [8]:
import numpy as np

# fix my broken code!

# HINTS
# math.sqrt(x) is the square root of x
# if v is an ndarray, np.conj(v) conjugates very element of v
# 

def norm_list(v):
    """
    v is a list
    """
    return 0.0

def vect_norm(v):
    """
    v is an ndarray
    """
    return 0.0

def cmplx_norm(v):
    """
    v is an ndarray of complex numbers
    """
    return 0.0

def test_norm(n,epsilon):
    v = np.random.random(n)
    w = np.random.random(n)
    vl = v.tolist()
    vi = v + 1.0j*w
    
    ans = np.linalg.norm(v)
    ans_i = np.linalg.norm(vi)
    if math.isclose(ans,norm_list(vl),abs_tol=epsilon):
        print("correct!")
    else:
        print("broken!")
    if math.isclose(ans,vect_norm(v),abs_tol=epsilon):
        print("correct!")
    else:
        print("broken!")
    if math.isclose(ans_i,cmplx_norm(vi),abs_tol=epsilon):
        print("correct!")
    else:
        print("broken!")
    
def time_norm(n):
    v = np.random.random(n)
    w = np.random.random(n)
    vl = v.tolist()
    vi = v + 1.0j*w
   
    print("")
    print("list version:")
    %time norm_list(vl)
    print("ndarray version")
    %time vect_norm(v)
    print("complext version")
    %time cmplx_norm(vi)

test_norm(100,0.0001)
time_norm(100)
time_norm(100000)
time_norm(100000000)
#time_norm(100000000000)



broken!
broken!
broken!

list version:
CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.2 µs
ndarray version
CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 4.77 µs
complext version
CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 4.77 µs

list version:
CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 5.96 µs
ndarray version
CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.72 µs
complext version
CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.25 µs

list version:
CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.91 µs
ndarray version
CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 5.96 µs
complext version
CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 5.01 µs


In [9]:
import numpy as np

# fix my broken code!


# HINTS
# if m is a matrix m[i,j] is the i-th row, j-th col
# and m[i,:] is the entire i-th row
# (row,cols) = m.shape  will give you the number of rows and cols, if you need this

def mat_vect_list(m,v):
    """
    m is a list of lists and v is a list
    e.g. m is [[1,0,0],[0,1,0],[0,0,1]]
    """
    w = [0.0]*len(v)
    return w

def mat_vect(m,v):
    """
    m and v and nd arrays. m is 2 dim and v is 1 dim
    """
    return np.zeros(len(v))


def test_mat_vect(n,epsilon):
    m = np.random.random(n*n)
    m.shape = (n,n)
    v = np.random.random(n)
    vl = v.tolist()
    ml = m.tolist()
    
    ans = np.dot(m,v)
    if np.allclose(ans,mat_vect_list(ml,vl),atol=epsilon):
        print("correct!")
    else:
        print("broken!")
    if np.allclose(ans,mat_vect(m,v),atol=epsilon):
        print("correct!")
    else:
        print("broken!")
        
def time_mat_vect(n):
    m = np.random.random(n*n)
    m.shape = (n,n)
    v = np.random.random(n)
    vl = v.tolist()
    ml = m.tolist()
    
    print("")
    print("n=%d ..."%(n))
    print("list version:")
    %time mat_vect_list(ml,vl)
    print("ndarry version:")
    %time mat_vect(m,v)

    
test_mat_vect(3,0.0001)

time_mat_vect(10)
time_mat_vect(100)
time_mat_vect(1000)
#time_mat_vect(10000)
print("\nDONE!")


broken!
broken!

n=10 ...
list version:
CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 5.96 µs
ndarry version:
CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 9.06 µs

n=100 ...
list version:
CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.15 µs
ndarry version:
CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 9.06 µs

n=1000 ...
list version:
CPU times: user 8 µs, sys: 4 µs, total: 12 µs
Wall time: 12.9 µs
ndarry version:
CPU times: user 12 µs, sys: 2 µs, total: 14 µs
Wall time: 16.9 µs

DONE!
